name: Release

on:
  push:
    branches: [master]

jobs:
  release-version:
    name: Release a new version using semantic release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.export.outputs.version }}
    steps:
      - name: Checkout repository (full-depth)
        uses: actions/checkout@v2
        with: { fetch-depth: 0 }
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
      - name: Export released version
        id: export
        run: echo "::set-output name=version::$(git describe --tags --abbrev=0)"

  build:
    name: Publish Python library to pip
    runs-on: ubuntu-latest
    needs: [release-version]
    env:
      RELEASE_TAG: ${{ needs.release-version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.6
      - name: Install project
        working-directory: .
        run: poetry install
      - name: Bump version & publish library
        working-directory: .
        run: |
          poetry version ${{ env.RELEASE_TAG }}
          poetry publish --build  -u __token__ -p ${{ secrets.PIP_PASSWORD }}
