name: Test

on: [push, pull_request]

jobs:
  pre-commit:
    name: Run pre-commit check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install using Pip
        run: python -m pip install pre-commit
      - name: Install pre-commit hook
        run: pre-commit install
      - name: Run pre-commit checks
        run: pre-commit run --verbose --all-files

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Update ubuntu
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends git gcc python3-dev
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install pytest
        run: pip3 install pytest==5.4.3
      - name: Install package
        run: poetry install
      - name: Run test suite
        run: pytest --color=yes --verbose --showlocals tests
